/* ==========================================================================
   PRODUCTS-DATA.JS
   This is the ONLY file you need to edit to change shop products.

   Each product looks like this:
   {n:"Arduino Uno", c:"Development Boards", p:"₹549", img:"https://..."},

   n   = Product Name        (shown as the card title)
   c   = Category            (must match one of the categories in
         PRODUCT_CATEGORIES below, or create a new one there too)
   p   = Price               (optional. Leave it out completely to show
         "Contact for Price". Format like "₹549")
   img = Photo URL           (optional. Paste your own photo link here.
         If you skip it, a random placeholder photo is used instead.
         You can upload photos to a free host like https://imgur.com or
         to a GitHub "images" folder in this same repo and paste that link.)

   HOW TO EDIT:
   - To change a name:  edit the text inside n:"..."
   - To change a price: edit the text inside p:"..." (or add p:"₹XXX" if missing)
   - To add a photo:    add  img:"https://your-photo-link.jpg"  before the closing }
   - To add a brand-new product: copy any line, change all 4 values, keep the comma at the end
   - To delete a product: delete its whole line
   - Do NOT remove the commas or curly braces { }
   ========================================================================== */

const PRODUCT_CATEGORIES = ["Basic Components", "Displays & Audio", "Development Boards", "Sensors", "Communication Modules", "Motors, Actuators & Drivers", "Power & Battery", "Relays & Timers", "Robotics & 3D Printing", "Connectors, Wires & Hardware", "Tools & Test Equipment", "Power Tools & Equipment"];

const PRODUCTS = [
{n:"Carbon Film Resistors",c:"Basic Components",img:"https://picsum.photos/seed/carbon-film-resistors/300/300"},
{n:"Metal Film Resistors",c:"Basic Components",img:"https://picsum.photos/seed/metal-film-resistors/300/300"},
{n:"Wirewound Resistors",c:"Basic Components",img:"https://picsum.photos/seed/wirewound-resistors/300/300"},
{n:"Variable Resistors (Potentiometers)",c:"Basic Components",img:"https://picsum.photos/seed/variable-resistors-potentiometers/300/300"},
{n:"Trimmer Potentiometers",c:"Basic Components",img:"https://picsum.photos/seed/trimmer-potentiometers/300/300"},
{n:"SMD Resistors",c:"Basic Components",img:"https://picsum.photos/seed/smd-resistors/300/300"},
{n:"Ceramic Capacitors",c:"Basic Components",p:"₹89",img:"https://picsum.photos/seed/ceramic-capacitors/300/300"},
{n:"Electrolytic Capacitors",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/electrolytic-capacitors/300/300"},
{n:"Tantalum Capacitors",c:"Basic Components",img:"https://picsum.photos/seed/tantalum-capacitors/300/300"},
{n:"Polyester Film Capacitors",c:"Basic Components",img:"https://picsum.photos/seed/polyester-film-capacitors/300/300"},
{n:"Variable Capacitors",c:"Basic Components",img:"https://picsum.photos/seed/variable-capacitors/300/300"},
{n:"SMD Capacitors",c:"Basic Components",img:"https://picsum.photos/seed/smd-capacitors/300/300"},
{n:"Rectifier Diodes (1N4007)",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/rectifier-diodes-1n4007/300/300"},
{n:"Zener Diodes",c:"Basic Components",img:"https://picsum.photos/seed/zener-diodes/300/300"},
{n:"Schottky Diodes",c:"Basic Components",img:"https://picsum.photos/seed/schottky-diodes/300/300"},
{n:"LEDs (Red, Green, Blue, White, Yellow)",c:"Basic Components",img:"https://picsum.photos/seed/leds-red-green-blue-white-yellow/300/300"},
{n:"RGB LEDs",c:"Basic Components",img:"https://picsum.photos/seed/rgb-leds/300/300"},
{n:"High Watt Power LEDs",c:"Basic Components",img:"https://picsum.photos/seed/high-watt-power-leds/300/300"},
{n:"SMD LEDs",c:"Basic Components",img:"https://picsum.photos/seed/smd-leds/300/300"},
{n:"Choke Coils",c:"Basic Components",img:"https://picsum.photos/seed/choke-coils/300/300"},
{n:"Ferrite Beads",c:"Basic Components",img:"https://picsum.photos/seed/ferrite-beads/300/300"},
{n:"SMD Inductors",c:"Basic Components",img:"https://picsum.photos/seed/smd-inductors/300/300"},
{n:"BJT Transistors (BC547, BC557, 2N2222, TIP122)",c:"Basic Components",img:"https://picsum.photos/seed/bjt-transistors-bc547-bc557-2n2222-tip122/300/300"},
{n:"MOSFET Transistors (IRF540, IRFZ44N)",c:"Basic Components",p:"₹39",img:"https://picsum.photos/seed/mosfet-transistors-irf540-irfz44n/300/300"},
{n:"Darlington Transistors",c:"Basic Components",img:"https://picsum.photos/seed/darlington-transistors/300/300"},
{n:"NE555 Timer IC",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/ne555-timer-ic/300/300"},
{n:"74HC Series Logic ICs",c:"Basic Components",img:"https://picsum.photos/seed/74hc-series-logic-ics/300/300"},
{n:"CD4000 Series Logic ICs",c:"Basic Components",img:"https://picsum.photos/seed/cd4000-series-logic-ics/300/300"},
{n:"Operational Amplifiers (LM358, LM741)",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/operational-amplifiers-lm358-lm741/300/300"},
{n:"Optocouplers (PC817)",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/optocouplers-pc817/300/300"},
{n:"MCP23017 I2C I/O Expander Modules",c:"Basic Components",img:"https://picsum.photos/seed/mcp23017-i2c-i-o-expander-modules/300/300"},
{n:"PCF8574 I/O Expansion Boards",c:"Basic Components",img:"https://picsum.photos/seed/pcf8574-i-o-expansion-boards/300/300"},
{n:"PCA9685 16-Channel PWM Drivers",c:"Basic Components",img:"https://picsum.photos/seed/pca9685-16-channel-pwm-drivers/300/300"},
{n:"CD74HC4067 16-Channel Analog Multiplexers",c:"Basic Components",img:"https://picsum.photos/seed/cd74hc4067-16-channel-analog-multiplexers/300/300"},
{n:"74HC595 Shift Register Modules",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/74hc595-shift-register-modules/300/300"},
{n:"MAX7219 Dot Matrix Display Driver Modules",c:"Basic Components",p:"₹59",img:"https://picsum.photos/seed/max7219-dot-matrix-display-driver-modules/300/300"},
{n:"ULN2003 Darlington Transistor Driver Boards",c:"Basic Components",img:"https://picsum.photos/seed/uln2003-darlington-transistor-driver-boards/300/300"},
{n:"RTC Modules (DS1307, DS3231)",c:"Basic Components",img:"https://picsum.photos/seed/rtc-modules-ds1307-ds3231/300/300"},
{n:"ADS1115 16-Bit 4-Channel ADC Module",c:"Basic Components",img:"https://picsum.photos/seed/ads1115-16-bit-4-channel-adc-module/300/300"},
{n:"Laser Diodes and Laser Transmitter Modules",c:"Basic Components",img:"https://picsum.photos/seed/laser-diodes-and-laser-transmitter-modules/300/300"},
{n:"IR Transmitter and Receiver Diodes",c:"Basic Components",p:"₹29",img:"https://picsum.photos/seed/ir-transmitter-and-receiver-diodes/300/300"},
{n:"Slide Potentiometers (Linear Faders)",c:"Basic Components",img:"https://picsum.photos/seed/slide-potentiometers-linear-faders/300/300"},
{n:"Multi-Turn Precision Potentiometers",c:"Basic Components",img:"https://picsum.photos/seed/multi-turn-precision-potentiometers/300/300"},
{n:"Trimpot Resistor Assortment Kits",c:"Basic Components",img:"https://picsum.photos/seed/trimpot-resistor-assortment-kits/300/300"},
{n:"Piezo Spark Igniters",c:"Basic Components",img:"https://picsum.photos/seed/piezo-spark-igniters/300/300"},
{n:"Resistor Color Code Guide Cards",c:"Basic Components",img:"https://picsum.photos/seed/resistor-color-code-guide-cards/300/300"},
{n:"ATmega328P Microcontroller IC (with Bootloader)",c:"Basic Components",img:"https://picsum.photos/seed/atmega328p-microcontroller-ic-with-bootloader/300/300"},
{n:"ATmega16A / ATmega32A Microcontroller ICs",c:"Basic Components",img:"https://picsum.photos/seed/atmega16a-atmega32a-microcontroller-ics/300/300"},
{n:"ATtiny85 Microcontroller IC",c:"Basic Components",img:"https://picsum.photos/seed/attiny85-microcontroller-ic/300/300"},
{n:"PIC Microcontrollers (PIC16F877A)",c:"Basic Components",img:"https://picsum.photos/seed/pic-microcontrollers-pic16f877a/300/300"},
{n:"7-Segment Displays",c:"Displays & Audio",img:"https://picsum.photos/seed/7-segment-displays/300/300"},
{n:"Dot Matrix Displays",c:"Displays & Audio",img:"https://picsum.photos/seed/dot-matrix-displays/300/300"},
{n:"LCD Displays (16x2, 20x4)",c:"Displays & Audio",img:"https://picsum.photos/seed/lcd-displays-16x2-20x4/300/300"},
{n:"OLED Displays",c:"Displays & Audio",img:"https://picsum.photos/seed/oled-displays/300/300"},
{n:"TFT Touch Screens",c:"Displays & Audio",img:"https://picsum.photos/seed/tft-touch-screens/300/300"},
{n:"TM1637 4-Digit 7-Segment Display Modules",c:"Displays & Audio",img:"https://picsum.photos/seed/tm1637-4-digit-7-segment-display-modules/300/300"},
{n:"Nokia 5110 LCD Displays",c:"Displays & Audio",img:"https://picsum.photos/seed/nokia-5110-lcd-displays/300/300"},
{n:"ST7735 1.8-Inch TFT Color Displays",c:"Displays & Audio",img:"https://picsum.photos/seed/st7735-1-8-inch-tft-color-displays/300/300"},
{n:"ILI9341 2.2-Inch TFT Touch Screens",c:"Displays & Audio",img:"https://picsum.photos/seed/ili9341-2-2-inch-tft-touch-screens/300/300"},
{n:"SSD1306 0.96-Inch OLED Displays",c:"Displays & Audio",img:"https://picsum.photos/seed/ssd1306-0-96-inch-oled-displays/300/300"},
{n:"SSD1309 2.42-Inch OLED Displays",c:"Displays & Audio",img:"https://picsum.photos/seed/ssd1309-2-42-inch-oled-displays/300/300"},
{n:"E-Paper Displays (2.9-Inch, 4.2-Inch)",c:"Displays & Audio",img:"https://picsum.photos/seed/e-paper-displays-2-9-inch-4-2-inch/300/300"},
{n:"DFPlayer Pro MP3 Modules",c:"Displays & Audio",img:"https://picsum.photos/seed/dfplayer-pro-mp3-modules/300/300"},
{n:"SYN6288 Text-to-Speech Modules",c:"Displays & Audio",img:"https://picsum.photos/seed/syn6288-text-to-speech-modules/300/300"},
{n:"ISD1820 Voice Recording and Playback Modules",c:"Displays & Audio",img:"https://picsum.photos/seed/isd1820-voice-recording-and-playback-modules/300/300"},
{n:"WT588D Voice Sound Modules",c:"Displays & Audio",img:"https://picsum.photos/seed/wt588d-voice-sound-modules/300/300"},
{n:"TPA3116D2 Dual Channel Amplifiers",c:"Displays & Audio",img:"https://picsum.photos/seed/tpa3116d2-dual-channel-amplifiers/300/300"},
{n:"PAM8610 15W+15W Dual Channel Audio Amplifiers",c:"Displays & Audio",img:"https://picsum.photos/seed/pam8610-15w-15w-dual-channel-audio-amplifiers/300/300"},
{n:"Bluetooth Audio Receiver Boards",c:"Displays & Audio",img:"https://picsum.photos/seed/bluetooth-audio-receiver-boards/300/300"},
{n:"FM Radio Receiver Modules",c:"Displays & Audio",img:"https://picsum.photos/seed/fm-radio-receiver-modules/300/300"},
{n:"Audio Amplifier ICs (TDA2030, PAM8403)",c:"Displays & Audio",img:"https://picsum.photos/seed/audio-amplifier-ics-tda2030-pam8403/300/300"},
{n:"Piezo Buzzers (Active and Passive)",c:"Displays & Audio",img:"https://picsum.photos/seed/piezo-buzzers-active-and-passive/300/300"},
{n:"Mini DC Speakers",c:"Displays & Audio",img:"https://picsum.photos/seed/mini-dc-speakers/300/300"},
{n:"MP3 Player Modules (DFPlayer Mini)",c:"Displays & Audio",img:"https://picsum.photos/seed/mp3-player-modules-dfplayer-mini/300/300"},
{n:"VS1053 MP3 / Audio Codec Modules",c:"Displays & Audio",img:"https://picsum.photos/seed/vs1053-mp3-audio-codec-modules/300/300"},
{n:"Audio Amplifier Boards (TDA7297, TPA3116D2)",c:"Displays & Audio",img:"https://picsum.photos/seed/audio-amplifier-boards-tda7297-tpa3116d2/300/300"},
{n:"Electret Condenser Microphones",c:"Displays & Audio",img:"https://picsum.photos/seed/electret-condenser-microphones/300/300"},
{n:"Piezoelectric Discs (Buzzer Elements)",c:"Displays & Audio",img:"https://picsum.photos/seed/piezoelectric-discs-buzzer-elements/300/300"},
{n:"Thermal Printers (TTL Serial Receipt Printers)",c:"Displays & Audio",img:"https://picsum.photos/seed/thermal-printers-ttl-serial-receipt-printers/300/300"},
{n:"Arduino Uno",c:"Development Boards",p:"₹549",img:"https://picsum.photos/seed/arduino-uno/300/300"},
{n:"Arduino Nano",c:"Development Boards",p:"₹299",img:"https://picsum.photos/seed/arduino-nano/300/300"},
{n:"Arduino Mega",c:"Development Boards",p:"₹949",img:"https://picsum.photos/seed/arduino-mega/300/300"},
{n:"Arduino Pro Mini",c:"Development Boards",p:"₹249",img:"https://picsum.photos/seed/arduino-pro-mini/300/300"},
{n:"Arduino Leonardo",c:"Development Boards",img:"https://picsum.photos/seed/arduino-leonardo/300/300"},
{n:"Arduino Due",c:"Development Boards",img:"https://picsum.photos/seed/arduino-due/300/300"},
{n:"Arduino Zero",c:"Development Boards",img:"https://picsum.photos/seed/arduino-zero/300/300"},
{n:"Teensy 3.2",c:"Development Boards",img:"https://picsum.photos/seed/teensy-3-2/300/300"},
{n:"Teensy 4.0 / 4.1",c:"Development Boards",img:"https://picsum.photos/seed/teensy-4-0-4-1/300/300"},
{n:"NodeMCU ESP32S",c:"Development Boards",img:"https://picsum.photos/seed/nodemcu-esp32s/300/300"},
{n:"ESP-WROOM-32",c:"Development Boards",img:"https://picsum.photos/seed/esp-wroom-32/300/300"},
{n:"ESP8266 NodeMCU",c:"Development Boards",p:"₹299",img:"https://picsum.photos/seed/esp8266-nodemcu/300/300"},
{n:"ESP32",c:"Development Boards",p:"₹449",img:"https://picsum.photos/seed/esp32/300/300"},
{n:"ESP32-CAM",c:"Development Boards",img:"https://picsum.photos/seed/esp32-cam/300/300"},
{n:"ESP32-CAM AI-Thinker Module with OV2640",c:"Development Boards",img:"https://picsum.photos/seed/esp32-cam-ai-thinker-module-with-ov2640/300/300"},
{n:"Raspberry Pi Pico",c:"Development Boards",p:"₹499",img:"https://picsum.photos/seed/raspberry-pi-pico/300/300"},
{n:"Raspberry Pi 4B / 5",c:"Development Boards",img:"https://picsum.photos/seed/raspberry-pi-4b-5/300/300"},
{n:"Raspberry Pi Zero 2 W",c:"Development Boards",img:"https://picsum.photos/seed/raspberry-pi-zero-2-w/300/300"},
{n:"Raspberry Pi Compute Modules",c:"Development Boards",img:"https://picsum.photos/seed/raspberry-pi-compute-modules/300/300"},
{n:"STM32 Development Boards",c:"Development Boards",img:"https://picsum.photos/seed/stm32-development-boards/300/300"},
{n:"Particle Boron",c:"Development Boards",img:"https://picsum.photos/seed/particle-boron/300/300"},
{n:"Particle Argon",c:"Development Boards",img:"https://picsum.photos/seed/particle-argon/300/300"},
{n:"Adafruit Feather Boards",c:"Development Boards",img:"https://picsum.photos/seed/adafruit-feather-boards/300/300"},
{n:"Adafruit Circuit Playground",c:"Development Boards",img:"https://picsum.photos/seed/adafruit-circuit-playground/300/300"},
{n:"BBC micro:bit",c:"Development Boards",img:"https://picsum.photos/seed/bbc-micro-bit/300/300"},
{n:"PyBoard",c:"Development Boards",img:"https://picsum.photos/seed/pyboard/300/300"},
{n:"Orange Pi Zero",c:"Development Boards",img:"https://picsum.photos/seed/orange-pi-zero/300/300"},
{n:"Banana Pi M3",c:"Development Boards",img:"https://picsum.photos/seed/banana-pi-m3/300/300"},
{n:"Odroid C4",c:"Development Boards",img:"https://picsum.photos/seed/odroid-c4/300/300"},
{n:"Banana Pi / Orange Pi Development Boards",c:"Development Boards",img:"https://picsum.photos/seed/banana-pi-orange-pi-development-boards/300/300"},
{n:"Arduino Sensor Shield",c:"Development Boards",img:"https://picsum.photos/seed/arduino-sensor-shield/300/300"},
{n:"NodeMCU ESP8266 Module",c:"Development Boards",img:"https://picsum.photos/seed/nodemcu-esp8266-module/300/300"},
{n:"ESP32-WROOM-32 Module",c:"Development Boards",img:"https://picsum.photos/seed/esp32-wroom-32-module/300/300"},
{n:"NodeMCU Base Expansion Boards",c:"Development Boards",img:"https://picsum.photos/seed/nodemcu-base-expansion-boards/300/300"},
{n:"AVR Programmers",c:"Development Boards",img:"https://picsum.photos/seed/avr-programmers/300/300"},
{n:"DHT11 Temperature & Humidity Sensor",c:"Sensors",p:"₹149",img:"https://picsum.photos/seed/dht11-temperature-humidity-sensor/300/300"},
{n:"DHT22 Temperature & Humidity Sensor",c:"Sensors",img:"https://picsum.photos/seed/dht22-temperature-humidity-sensor/300/300"},
{n:"BMP180 Barometric Pressure Sensor",c:"Sensors",img:"https://picsum.photos/seed/bmp180-barometric-pressure-sensor/300/300"},
{n:"BME280 Environment Sensor",c:"Sensors",img:"https://picsum.photos/seed/bme280-environment-sensor/300/300"},
{n:"MQ Series Gas Sensors (MQ-2, MQ-3, MQ-135)",c:"Sensors",img:"https://picsum.photos/seed/mq-series-gas-sensors-mq-2-mq-3-mq-135/300/300"},
{n:"PIR Motion Sensor",c:"Sensors",p:"₹99",img:"https://picsum.photos/seed/pir-motion-sensor/300/300"},
{n:"Ultrasonic Sensor (HC-SR04)",c:"Sensors",p:"₹69",img:"https://picsum.photos/seed/ultrasonic-sensor-hc-sr04/300/300"},
{n:"Accelerometer & Gyroscope (MPU6050)",c:"Sensors",p:"₹199",img:"https://picsum.photos/seed/accelerometer-gyroscope-mpu6050/300/300"},
{n:"Tilt Sensor",c:"Sensors",img:"https://picsum.photos/seed/tilt-sensor/300/300"},
{n:"Vibration Sensor",c:"Sensors",img:"https://picsum.photos/seed/vibration-sensor/300/300"},
{n:"IR Obstacle/Line Tracking Sensor",c:"Sensors",img:"https://picsum.photos/seed/ir-obstacle-line-tracking-sensor/300/300"},
{n:"Fingerprint Sensor Module",c:"Sensors",img:"https://picsum.photos/seed/fingerprint-sensor-module/300/300"},
{n:"OV2640 Camera Module",c:"Sensors",img:"https://picsum.photos/seed/ov2640-camera-module/300/300"},
{n:"Sound / Microphone Sensors (KY-037, MAX9814)",c:"Sensors",img:"https://picsum.photos/seed/sound-microphone-sensors-ky-037-max9814/300/300"},
{n:"Flame Sensors",c:"Sensors",img:"https://picsum.photos/seed/flame-sensors/300/300"},
{n:"Rain Drop Sensors",c:"Sensors",img:"https://picsum.photos/seed/rain-drop-sensors/300/300"},
{n:"Soil Moisture Sensors",c:"Sensors",p:"₹59",img:"https://picsum.photos/seed/soil-moisture-sensors/300/300"},
{n:"Water Level Sensors",c:"Sensors",img:"https://picsum.photos/seed/water-level-sensors/300/300"},
{n:"Light Dependent Resistors (LDR)",c:"Sensors",img:"https://picsum.photos/seed/light-dependent-resistors-ldr/300/300"},
{n:"TCS3200 Color Sensor",c:"Sensors",p:"₹299",img:"https://picsum.photos/seed/tcs3200-color-sensor/300/300"},
{n:"MAX30100 / MAX30102 Heart Rate & Pulse Oximeter Sensors",c:"Sensors",img:"https://picsum.photos/seed/max30100-max30102-heart-rate-pulse-oximeter-sensors/300/300"},
{n:"MLX90614 Infrared Thermometer Sensor",c:"Sensors",img:"https://picsum.photos/seed/mlx90614-infrared-thermometer-sensor/300/300"},
{n:"TTP223 Touch Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/ttp223-touch-sensor-modules/300/300"},
{n:"Reed Switches",c:"Sensors",img:"https://picsum.photos/seed/reed-switches/300/300"},
{n:"Magnetic Door Contact Sensors",c:"Sensors",img:"https://picsum.photos/seed/magnetic-door-contact-sensors/300/300"},
{n:"Opto-Interrupter Modules",c:"Sensors",img:"https://picsum.photos/seed/opto-interrupter-modules/300/300"},
{n:"Hall Effect Sensors (3144)",c:"Sensors",img:"https://picsum.photos/seed/hall-effect-sensors-3144/300/300"},
{n:"Current Sensors (ACS712 - 5A, 20A, 30A)",c:"Sensors",img:"https://picsum.photos/seed/current-sensors-acs712-5a-20a-30a/300/300"},
{n:"Voltage Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/voltage-sensor-modules/300/300"},
{n:"Load Cell Weight Sensors (1kg, 5kg, 10kg, 50kg)",c:"Sensors",img:"https://picsum.photos/seed/load-cell-weight-sensors-1kg-5kg-10kg-50kg/300/300"},
{n:"HX711 Load Cell Amplifier Modules",c:"Sensors",img:"https://picsum.photos/seed/hx711-load-cell-amplifier-modules/300/300"},
{n:"INA219 High Side DC Current Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/ina219-high-side-dc-current-sensor-modules/300/300"},
{n:"ACS758 Heavy Duty Current Sensors",c:"Sensors",img:"https://picsum.photos/seed/acs758-heavy-duty-current-sensors/300/300"},
{n:"WCS1800 Current Sensors",c:"Sensors",img:"https://picsum.photos/seed/wcs1800-current-sensors/300/300"},
{n:"ZMPT101B AC Voltage Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/zmpt101b-ac-voltage-sensor-modules/300/300"},
{n:"PZEM-004T AC Energy Meters",c:"Sensors",img:"https://picsum.photos/seed/pzem-004t-ac-energy-meters/300/300"},
{n:"SCT-013 Non-Invasive AC Current Clamp Sensors",c:"Sensors",img:"https://picsum.photos/seed/sct-013-non-invasive-ac-current-clamp-sensors/300/300"},
{n:"DS18B20 Waterproof Temperature Sensors",c:"Sensors",img:"https://picsum.photos/seed/ds18b20-waterproof-temperature-sensors/300/300"},
{n:"PT100 RTD Temperature Sensors",c:"Sensors",img:"https://picsum.photos/seed/pt100-rtd-temperature-sensors/300/300"},
{n:"K-Type Thermocouple Probes with MAX6675 Modules",c:"Sensors",img:"https://picsum.photos/seed/k-type-thermocouple-probes-with-max6675-modules/300/300"},
{n:"SEN0193 Capacitive Soil Moisture Sensors",c:"Sensors",img:"https://picsum.photos/seed/sen0193-capacitive-soil-moisture-sensors/300/300"},
{n:"MQ-138 Gas Sensors",c:"Sensors",img:"https://picsum.photos/seed/mq-138-gas-sensors/300/300"},
{n:"MQ-8 Hydrogen Gas Detectors",c:"Sensors",img:"https://picsum.photos/seed/mq-8-hydrogen-gas-detectors/300/300"},
{n:"MQ-9 Carbon Monoxide and Methane Sensors",c:"Sensors",img:"https://picsum.photos/seed/mq-9-carbon-monoxide-and-methane-sensors/300/300"},
{n:"MG811 Carbon Dioxide CO2 Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/mg811-carbon-dioxide-co2-sensor-modules/300/300"},
{n:"ZE08-CH2O Formaldehyde Gas Sensors",c:"Sensors",img:"https://picsum.photos/seed/ze08-ch2o-formaldehyde-gas-sensors/300/300"},
{n:"MP503 Air Quality Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/mp503-air-quality-sensor-modules/300/300"},
{n:"SEN0248 Laser Dust Sensors",c:"Sensors",img:"https://picsum.photos/seed/sen0248-laser-dust-sensors/300/300"},
{n:"PMS7003 Particulate Matter Air Sensors",c:"Sensors",img:"https://picsum.photos/seed/pms7003-particulate-matter-air-sensors/300/300"},
{n:"MiCS-5524 Gas Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/mics-5524-gas-sensor-modules/300/300"},
{n:"SEN0205 Liquid Flow Meters",c:"Sensors",img:"https://picsum.photos/seed/sen0205-liquid-flow-meters/300/300"},
{n:"YF-B5 Water Flow Sensors",c:"Sensors",img:"https://picsum.photos/seed/yf-b5-water-flow-sensors/300/300"},
{n:"FS400A Water Flow Switches",c:"Sensors",img:"https://picsum.photos/seed/fs400a-water-flow-switches/300/300"},
{n:"DN25 Brass Water Flow Sensors",c:"Sensors",img:"https://picsum.photos/seed/dn25-brass-water-flow-sensors/300/300"},
{n:"Non-Invasive Liquid Level Sensors",c:"Sensors",img:"https://picsum.photos/seed/non-invasive-liquid-level-sensors/300/300"},
{n:"Optical Liquid Level Switches",c:"Sensors",img:"https://picsum.photos/seed/optical-liquid-level-switches/300/300"},
{n:"Float Level Switches",c:"Sensors",img:"https://picsum.photos/seed/float-level-switches/300/300"},
{n:"Stainless Steel Float Switches",c:"Sensors",img:"https://picsum.photos/seed/stainless-steel-float-switches/300/300"},
{n:"Water Leak Detection Sensor Ropes",c:"Sensors",img:"https://picsum.photos/seed/water-leak-detection-sensor-ropes/300/300"},
{n:"Soil Salinity Sensors",c:"Sensors",img:"https://picsum.photos/seed/soil-salinity-sensors/300/300"},
{n:"VL53L0X Time-of-Flight Laser Distance Sensors",c:"Sensors",img:"https://picsum.photos/seed/vl53l0x-time-of-flight-laser-distance-sensors/300/300"},
{n:"VL53L1X Long Range ToF Sensors",c:"Sensors",img:"https://picsum.photos/seed/vl53l1x-long-range-tof-sensors/300/300"},
{n:"GP2Y0A21YK0F Infrared Distance Sensors",c:"Sensors",img:"https://picsum.photos/seed/gp2y0a21yk0f-infrared-distance-sensors/300/300"},
{n:"GP2Y0A02YK0F Sharp IR Sensors",c:"Sensors",img:"https://picsum.photos/seed/gp2y0a02yk0f-sharp-ir-sensors/300/300"},
{n:"HC-SR05 Ultrasonic Sensors",c:"Sensors",img:"https://picsum.photos/seed/hc-sr05-ultrasonic-sensors/300/300"},
{n:"US-015 High Precision Ultrasonic Sensors",c:"Sensors",img:"https://picsum.photos/seed/us-015-high-precision-ultrasonic-sensors/300/300"},
{n:"TFmini Micro LiDAR Distance Sensors",c:"Sensors",img:"https://picsum.photos/seed/tfmini-micro-lidar-distance-sensors/300/300"},
{n:"YD-LiDAR Kits",c:"Sensors",img:"https://picsum.photos/seed/yd-lidar-kits/300/300"},
{n:"RPLIDAR A1 360-Degree Laser Scanners",c:"Sensors",img:"https://picsum.photos/seed/rplidar-a1-360-degree-laser-scanners/300/300"},
{n:"ADXL345 3-Axis Accelerometers",c:"Sensors",img:"https://picsum.photos/seed/adxl345-3-axis-accelerometers/300/300"},
{n:"MPU9250 9-Axis Motion Tracking Sensors",c:"Sensors",img:"https://picsum.photos/seed/mpu9250-9-axis-motion-tracking-sensors/300/300"},
{n:"ICM-20948 9-Axis IMU Modules",c:"Sensors",img:"https://picsum.photos/seed/icm-20948-9-axis-imu-modules/300/300"},
{n:"BNO055 9-Axis Absolute Orientation Sensors",c:"Sensors",img:"https://picsum.photos/seed/bno055-9-axis-absolute-orientation-sensors/300/300"},
{n:"HMC5883L Triple Axis Magnetometer Compass Modules",c:"Sensors",img:"https://picsum.photos/seed/hmc5883l-triple-axis-magnetometer-compass-modules/300/300"},
{n:"QMC5883L Digital Compass Modules",c:"Sensors",img:"https://picsum.photos/seed/qmc5883l-digital-compass-modules/300/300"},
{n:"ADXL335 Analog Accelerometers",c:"Sensors",img:"https://picsum.photos/seed/adxl335-analog-accelerometers/300/300"},
{n:"MMA7361 3-Axis Accelerometer Modules",c:"Sensors",img:"https://picsum.photos/seed/mma7361-3-axis-accelerometer-modules/300/300"},
{n:"GY-302 BH1750 Digital Light Intensity Sensors",c:"Sensors",img:"https://picsum.photos/seed/gy-302-bh1750-digital-light-intensity-sensors/300/300"},
{n:"TSL2561 Luminosity Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/tsl2561-luminosity-sensor-modules/300/300"},
{n:"APDS-9960 Proximity, Gesture and RGB Color Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/apds-9960-proximity-gesture-and-rgb-color-sensor-modules/300/300"},
{n:"BH1750FVI Ambient Light Sensors",c:"Sensors",img:"https://picsum.photos/seed/bh1750fvi-ambient-light-sensors/300/300"},
{n:"VEML6075 UVA/UVB Ultraviolet Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/veml6075-uva-uvb-ultraviolet-sensor-modules/300/300"},
{n:"Si1145 UV Index IR Visible Light Sensors",c:"Sensors",img:"https://picsum.photos/seed/si1145-uv-index-ir-visible-light-sensors/300/300"},
{n:"AD8232 ECG Heart Rate Monitor Modules",c:"Sensors",img:"https://picsum.photos/seed/ad8232-ecg-heart-rate-monitor-modules/300/300"},
{n:"Pulse Sensor Amped",c:"Sensors",img:"https://picsum.photos/seed/pulse-sensor-amped/300/300"},
{n:"SEN0213 GSR Galvanic Skin Response Sensors",c:"Sensors",img:"https://picsum.photos/seed/sen0213-gsr-galvanic-skin-response-sensors/300/300"},
{n:"Gravity Analog Sound Level Meters",c:"Sensors",img:"https://picsum.photos/seed/gravity-analog-sound-level-meters/300/300"},
{n:"SEN0232 Speech Recognition Modules",c:"Sensors",img:"https://picsum.photos/seed/sen0232-speech-recognition-modules/300/300"},
{n:"LD2410 24GHz Human Presence Radar Sensors",c:"Sensors",img:"https://picsum.photos/seed/ld2410-24ghz-human-presence-radar-sensors/300/300"},
{n:"HLK-LD2410C Millimeter Wave Radar Modules",c:"Sensors",img:"https://picsum.photos/seed/hlk-ld2410c-millimeter-wave-radar-modules/300/300"},
{n:"RCWL-0516 Microwave Radar Motion Detector Modules",c:"Sensors",img:"https://picsum.photos/seed/rcwl-0516-microwave-radar-motion-detector-modules/300/300"},
{n:"Filament Runout Sensors",c:"Sensors",img:"https://picsum.photos/seed/filament-runout-sensors/300/300"},
{n:"BLTouch Auto Bed Leveling Sensors",c:"Sensors",img:"https://picsum.photos/seed/bltouch-auto-bed-leveling-sensors/300/300"},
{n:"Fingerprint Scanners (R305 / R307 optical)",c:"Sensors",img:"https://picsum.photos/seed/fingerprint-scanners-r305-r307-optical/300/300"},
{n:"Laser Receiver Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/laser-receiver-sensor-modules/300/300"},
{n:"Color Recognition Sensors (TCS230 / TCS3200)",c:"Sensors",img:"https://picsum.photos/seed/color-recognition-sensors-tcs230-tcs3200/300/300"},
{n:"UV Radiation Sensors (GUVA-S12SD)",c:"Sensors",img:"https://picsum.photos/seed/uv-radiation-sensors-guva-s12sd/300/300"},
{n:"Solar Radiation & Light Intensity Sensors (BH1750)",c:"Sensors",img:"https://picsum.photos/seed/solar-radiation-light-intensity-sensors-bh1750/300/300"},
{n:"Turbidity Water Sensors",c:"Sensors",img:"https://picsum.photos/seed/turbidity-water-sensors/300/300"},
{n:"TDS Meters / Sensors",c:"Sensors",img:"https://picsum.photos/seed/tds-meters-sensors/300/300"},
{n:"Flow Rate Sensors (Water Flow Meters - YF-S201)",c:"Sensors",p:"₹349",img:"https://picsum.photos/seed/flow-rate-sensors-water-flow-meters-yf-s201/300/300"},
{n:"pH Sensor Modules for Water Testing",c:"Sensors",img:"https://picsum.photos/seed/ph-sensor-modules-for-water-testing/300/300"},
{n:"Flame Detection IR Sensors",c:"Sensors",img:"https://picsum.photos/seed/flame-detection-ir-sensors/300/300"},
{n:"Alcohol Breathalyzer Modules (MQ-3)",c:"Sensors",img:"https://picsum.photos/seed/alcohol-breathalyzer-modules-mq-3/300/300"},
{n:"Carbon Monoxide Detectors (MQ-7)",c:"Sensors",img:"https://picsum.photos/seed/carbon-monoxide-detectors-mq-7/300/300"},
{n:"Methane / LPG Leak Detectors (MQ-6)",c:"Sensors",img:"https://picsum.photos/seed/methane-lpg-leak-detectors-mq-6/300/300"},
{n:"Dust Sensors (GP2Y1010AU0F)",c:"Sensors",img:"https://picsum.photos/seed/dust-sensors-gp2y1010au0f/300/300"},
{n:"Heart Rate & SpO2 Sensors (MAX30100)",c:"Sensors",img:"https://picsum.photos/seed/heart-rate-spo2-sensors-max30100/300/300"},
{n:"EMG Muscle Sensor Myoware Boards",c:"Sensors",img:"https://picsum.photos/seed/emg-muscle-sensor-myoware-boards/300/300"},
{n:"EEG Brain-Wave Sensor Modules",c:"Sensors",img:"https://picsum.photos/seed/eeg-brain-wave-sensor-modules/300/300"},
{n:"Flex Sensors (Bending Sensors)",c:"Sensors",img:"https://picsum.photos/seed/flex-sensors-bending-sensors/300/300"},
{n:"Force Sensitive Resistors (FSR)",c:"Sensors",img:"https://picsum.photos/seed/force-sensitive-resistors-fsr/300/300"},
{n:"Piezo Vibration Sensors",c:"Sensors",img:"https://picsum.photos/seed/piezo-vibration-sensors/300/300"},
{n:"Rotary Encoders (KY-040)",c:"Sensors",img:"https://picsum.photos/seed/rotary-encoders-ky-040/300/300"},
{n:"NTC Thermistors (100K for 3D Printers)",c:"Sensors",img:"https://picsum.photos/seed/ntc-thermistors-100k-for-3d-printers/300/300"},
{n:"Bluetooth Module (HC-05, HC-06)",c:"Communication Modules",p:"₹349",img:"https://picsum.photos/seed/bluetooth-module-hc-05-hc-06/300/300"},
{n:"NRF24L01 Wireless Module",c:"Communication Modules",p:"₹89",img:"https://picsum.photos/seed/nrf24l01-wireless-module/300/300"},
{n:"GSM Module (SIM800L)",c:"Communication Modules",p:"₹499",img:"https://picsum.photos/seed/gsm-module-sim800l/300/300"},
{n:"RFID Reader (RC522)",c:"Communication Modules",p:"₹199",img:"https://picsum.photos/seed/rfid-reader-rc522/300/300"},
{n:"FT232H USB to SPI/I2C/UART Interface Converters",c:"Communication Modules",img:"https://picsum.photos/seed/ft232h-usb-to-spi-i2c-uart-interface-converters/300/300"},
{n:"CP2112 USB to I2C Communication Bridges",c:"Communication Modules",img:"https://picsum.photos/seed/cp2112-usb-to-i2c-communication-bridges/300/300"},
{n:"CH341A USB Programmer Boards",c:"Communication Modules",img:"https://picsum.photos/seed/ch341a-usb-programmer-boards/300/300"},
{n:"USB to RS485 Converters",c:"Communication Modules",img:"https://picsum.photos/seed/usb-to-rs485-converters/300/300"},
{n:"RS232 to RS485 Bi-Directional Converters",c:"Communication Modules",img:"https://picsum.photos/seed/rs232-to-rs485-bi-directional-converters/300/300"},
{n:"Ethernet to Serial TCP/IP Server Modules",c:"Communication Modules",img:"https://picsum.photos/seed/ethernet-to-serial-tcp-ip-server-modules/300/300"},
{n:"Serial to Wi-Fi Modules (USR-W610)",c:"Communication Modules",img:"https://picsum.photos/seed/serial-to-wi-fi-modules-usr-w610/300/300"},
{n:"SIM800C GSM/GPRS Shield Boards",c:"Communication Modules",img:"https://picsum.photos/seed/sim800c-gsm-gprs-shield-boards/300/300"},
{n:"A6 GSM/GPRS Modules",c:"Communication Modules",img:"https://picsum.photos/seed/a6-gsm-gprs-modules/300/300"},
{n:"SIM7000C NB-IoT/LTE-M/GPS All-in-One Modules",c:"Communication Modules",img:"https://picsum.photos/seed/sim7000c-nb-iot-lte-m-gps-all-in-one-modules/300/300"},
{n:"SIM7600CE 4G LTE Modules with GNSS",c:"Communication Modules",img:"https://picsum.photos/seed/sim7600ce-4g-lte-modules-with-gnss/300/300"},
{n:"SIM808 GPS/GSM Tracking Modules",c:"Communication Modules",img:"https://picsum.photos/seed/sim808-gps-gsm-tracking-modules/300/300"},
{n:"ATGM336H GPS/BDS Dual-Mode Navigation Modules",c:"Communication Modules",img:"https://picsum.photos/seed/atgm336h-gps-bds-dual-mode-navigation-modules/300/300"},
{n:"NEO-M8N High Precision GPS Modules",c:"Communication Modules",img:"https://picsum.photos/seed/neo-m8n-high-precision-gps-modules/300/300"},
{n:"RTK GPS Base Stations",c:"Communication Modules",img:"https://picsum.photos/seed/rtk-gps-base-stations/300/300"},
{n:"SX1280 2.4GHz LoRa Modules",c:"Communication Modules",img:"https://picsum.photos/seed/sx1280-2-4ghz-lora-modules/300/300"},
{n:"HopeRF RFM95W LoRa Transceiver Modules",c:"Communication Modules",img:"https://picsum.photos/seed/hoperf-rfm95w-lora-transceiver-modules/300/300"},
{n:"RFM69HCW High Power RF Transceiver Modules",c:"Communication Modules",img:"https://picsum.photos/seed/rfm69hcw-high-power-rf-transceiver-modules/300/300"},
{n:"CC1101 Wireless Transceiver Modules",c:"Communication Modules",img:"https://picsum.photos/seed/cc1101-wireless-transceiver-modules/300/300"},
{n:"NRF905 Wireless Data Transmission Modules",c:"Communication Modules",img:"https://picsum.photos/seed/nrf905-wireless-data-transmission-modules/300/300"},
{n:"APC220 Wireless RF Communication Modules",c:"Communication Modules",img:"https://picsum.photos/seed/apc220-wireless-rf-communication-modules/300/300"},
{n:"HC-12 SI4438 Wireless Serial Modules",c:"Communication Modules",img:"https://picsum.photos/seed/hc-12-si4438-wireless-serial-modules/300/300"},
{n:"E32-TTL-100 LoRa Modules",c:"Communication Modules",img:"https://picsum.photos/seed/e32-ttl-100-lora-modules/300/300"},
{n:"LoRa SX1276 / SX1278 Wireless Modules",c:"Communication Modules",img:"https://picsum.photos/seed/lora-sx1276-sx1278-wireless-modules/300/300"},
{n:"Zigbee Modules (CC2530)",c:"Communication Modules",img:"https://picsum.photos/seed/zigbee-modules-cc2530/300/300"},
{n:"nRF52832 Bluetooth Low Energy (BLE) Module",c:"Communication Modules",img:"https://picsum.photos/seed/nrf52832-bluetooth-low-energy-ble-module/300/300"},
{n:"SIM900A GSM/GPRS Module",c:"Communication Modules",img:"https://picsum.photos/seed/sim900a-gsm-gprs-module/300/300"},
{n:"GPS Modules (NEO-6M, NEO-M8N)",c:"Communication Modules",p:"₹549",img:"https://picsum.photos/seed/gps-modules-neo-6m-neo-m8n/300/300"},
{n:"Ethernet Module (ENC28J60, W5500)",c:"Communication Modules",img:"https://picsum.photos/seed/ethernet-module-enc28j60-w5500/300/300"},
{n:"USB to TTL Converters (CP2102, CH340, FT232RL)",c:"Communication Modules",img:"https://picsum.photos/seed/usb-to-ttl-converters-cp2102-ch340-ft232rl/300/300"},
{n:"MAX232 RS232 to TTL Communication ICs",c:"Communication Modules",img:"https://picsum.photos/seed/max232-rs232-to-ttl-communication-ics/300/300"},
{n:"CAN Bus Modules (MCP2515)",c:"Communication Modules",img:"https://picsum.photos/seed/can-bus-modules-mcp2515/300/300"},
{n:"RFID Keyfobs and Cards",c:"Communication Modules",img:"https://picsum.photos/seed/rfid-keyfobs-and-cards/300/300"},
{n:"RFID ID/IC Card Writers and Copiers",c:"Communication Modules",img:"https://picsum.photos/seed/rfid-id-ic-card-writers-and-copiers/300/300"},
{n:"SIM7600 4G LTE Communication Modules",c:"Communication Modules",img:"https://picsum.photos/seed/sim7600-4g-lte-communication-modules/300/300"},
{n:"SX1262 High Power LoRa Modules",c:"Communication Modules",img:"https://picsum.photos/seed/sx1262-high-power-lora-modules/300/300"},
{n:"nRF24L01+ with PA and LNA Antenna Modules",c:"Communication Modules",img:"https://picsum.photos/seed/nrf24l01-with-pa-and-lna-antenna-modules/300/300"},
{n:"MAX485 TTL to RS485 Communication Modules",c:"Communication Modules",img:"https://picsum.photos/seed/max485-ttl-to-rs485-communication-modules/300/300"},
{n:"Bluetooth Low Energy Beacons",c:"Communication Modules",img:"https://picsum.photos/seed/bluetooth-low-energy-beacons/300/300"},
{n:"Arduino Motor Shield",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/arduino-motor-shield/300/300"},
{n:"L293D Motor Shield Boards",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/l293d-motor-shield-boards/300/300"},
{n:"DC Toy Motors",c:"Motors, Actuators & Drivers",p:"₹19",img:"https://picsum.photos/seed/dc-toy-motors/300/300"},
{n:"BO Motors (Single and Dual Shaft)",c:"Motors, Actuators & Drivers",p:"₹69",img:"https://picsum.photos/seed/bo-motors-single-and-dual-shaft/300/300"},
{n:"Stepper Motors (NEMA 17, 28BYJ-48)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/stepper-motors-nema-17-28byj-48/300/300"},
{n:"Servo Motors (SG90, MG996R)",c:"Motors, Actuators & Drivers",p:"₹149",img:"https://picsum.photos/seed/servo-motors-sg90-mg996r/300/300"},
{n:"Coreless Motors",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/coreless-motors/300/300"},
{n:"Mini Submersible Water Pumps",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/mini-submersible-water-pumps/300/300"},
{n:"L298N Motor Driver",c:"Motors, Actuators & Drivers",p:"₹199",img:"https://picsum.photos/seed/l298n-motor-driver/300/300"},
{n:"L293D Motor Driver",c:"Motors, Actuators & Drivers",p:"₹49",img:"https://picsum.photos/seed/l293d-motor-driver/300/300"},
{n:"PCA9685 Servo Driver",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/pca9685-servo-driver/300/300"},
{n:"MOSFET Driver Modules (F530N / IRF520)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/mosfet-driver-modules-f530n-irf520/300/300"},
{n:"PWM DC Motor Speed Controllers",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/pwm-dc-motor-speed-controllers/300/300"},
{n:"Linear Actuators (12V)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/linear-actuators-12v/300/300"},
{n:"Solenoid Valves (Water and Air)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/solenoid-valves-water-and-air/300/300"},
{n:"Mini Air Pumps (12V / 6V)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/mini-air-pumps-12v-6v/300/300"},
{n:"High Torque DC Gear Motors",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/high-torque-dc-gear-motors/300/300"},
{n:"Heavy Duty Window Wiper Motors",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/heavy-duty-window-wiper-motors/300/300"},
{n:"Worm Gear DC Motors",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/worm-gear-dc-motors/300/300"},
{n:"Planetary Gearbox DC Motors",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/planetary-gearbox-dc-motors/300/300"},
{n:"Coreless Micro Motors (7x20mm, 8x20mm)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/coreless-micro-motors-7x20mm-8x20mm/300/300"},
{n:"High Speed Brushless DC Motors (BLDC)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/high-speed-brushless-dc-motors-bldc/300/300"},
{n:"Outrunner Brushless Motors for Drones",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/outrunner-brushless-motors-for-drones/300/300"},
{n:"ESC (Electronic Speed Controllers for Drones)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/esc-electronic-speed-controllers-for-drones/300/300"},
{n:"Propellers (CW and CCW Plastic/Carbon Fiber)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/propellers-cw-and-ccw-plastic-carbon-fiber/300/300"},
{n:"Quadcopter Drone Frames",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/quadcopter-drone-frames/300/300"},
{n:"Heavy Duty Linear Actuators with Feedback",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/heavy-duty-linear-actuators-with-feedback/300/300"},
{n:"Micro Linear Actuators (5V/12V)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/micro-linear-actuators-5v-12v/300/300"},
{n:"Electric Rolling Shutter Motors",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/electric-rolling-shutter-motors/300/300"},
{n:"DC Miniature Solenoids (Push-Pull Type)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/dc-miniature-solenoids-push-pull-type/300/300"},
{n:"Heavy Duty Electromagnets (100kg holding force)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/heavy-duty-electromagnets-100kg-holding-force/300/300"},
{n:"Piezoelectric Ultrasonic Transducers",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/piezoelectric-ultrasonic-transducers/300/300"},
{n:"Shape Memory Alloy Spring Actuators",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/shape-memory-alloy-spring-actuators/300/300"},
{n:"Peristaltic Dosing Pumps (12V/24V)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/peristaltic-dosing-pumps-12v-24v/300/300"},
{n:"High Pressure Diaphragm Water Pumps",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/high-pressure-diaphragm-water-pumps/300/300"},
{n:"DC Brushless Cooling Fans (5V, 12V, 24V)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/dc-brushless-cooling-fans-5v-12v-24v/300/300"},
{n:"Radial Blower Fans (Turbo Fans)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/radial-blower-fans-turbo-fans/300/300"},
{n:"Water Cooling Pumps for PC/Projects",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/water-cooling-pumps-for-pc-projects/300/300"},
{n:"Pneumatic Air Valves and Tubing",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/pneumatic-air-valves-and-tubing/300/300"},
{n:"Mini Vacuum Pumps (12V)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/mini-vacuum-pumps-12v/300/300"},
{n:"Solenoid Door Locks (12V Electronic Latches)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/solenoid-door-locks-12v-electronic-latches/300/300"},
{n:"Electromagnets (Heavy Duty 12V / 24V Lifting Magnets)",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/electromagnets-heavy-duty-12v-24v-lifting-magnets/300/300"},
{n:"Shape Memory Alloy (SMA) Wires",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/shape-memory-alloy-sma-wires/300/300"},
{n:"Piezo Actuators",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/piezo-actuators/300/300"},
{n:"A4988 Stepper Motor Driver Modules",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/a4988-stepper-motor-driver-modules/300/300"},
{n:"DRV8825 Stepper Motor Drivers",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/drv8825-stepper-motor-drivers/300/300"},
{n:"TMC2208 / TMC2209 Ultra-Silent Stepper Drivers",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/tmc2208-tmc2209-ultra-silent-stepper-drivers/300/300"},
{n:"TB6600 High Power Stepper Motor Drivers",c:"Motors, Actuators & Drivers",img:"https://picsum.photos/seed/tb6600-high-power-stepper-motor-drivers/300/300"},
{n:"Voltage Regulator ICs (7805, 7812, 7905, LM317, AMS1117)",c:"Power & Battery",img:"https://picsum.photos/seed/voltage-regulator-ics-7805-7812-7905-lm317-ams1117/300/300"},
{n:"Step-down DC-DC Converter (LM2596)",c:"Power & Battery",p:"₹149",img:"https://picsum.photos/seed/step-down-dc-dc-converter-lm2596/300/300"},
{n:"Step-up DC-DC Converter (XL6009)",c:"Power & Battery",p:"₹149",img:"https://picsum.photos/seed/step-up-dc-dc-converter-xl6009/300/300"},
{n:"Li-ion Cells (18650)",c:"Power & Battery",p:"₹149",img:"https://picsum.photos/seed/li-ion-cells-18650/300/300"},
{n:"LiPo Batteries (3.7V, 7.4V, 11.1V)",c:"Power & Battery",img:"https://picsum.photos/seed/lipo-batteries-3-7v-7-4v-11-1v/300/300"},
{n:"9V Batteries",c:"Power & Battery",img:"https://picsum.photos/seed/9v-batteries/300/300"},
{n:"Coin Cell Batteries (CR2032)",c:"Power & Battery",img:"https://picsum.photos/seed/coin-cell-batteries-cr2032/300/300"},
{n:"Lead-Acid Batteries",c:"Power & Battery",img:"https://picsum.photos/seed/lead-acid-batteries/300/300"},
{n:"TP4056 Li-ion Charging Modules",c:"Power & Battery",p:"₹39",img:"https://picsum.photos/seed/tp4056-li-ion-charging-modules/300/300"},
{n:"Battery Management Systems (BMS - 1S, 2S, 3S, 4S)",c:"Power & Battery",img:"https://picsum.photos/seed/battery-management-systems-bms-1s-2s-3s-4s/300/300"},
{n:"Battery Holders",c:"Power & Battery",img:"https://picsum.photos/seed/battery-holders/300/300"},
{n:"5V SMPS Power Supplies",c:"Power & Battery",img:"https://picsum.photos/seed/5v-smps-power-supplies/300/300"},
{n:"12V SMPS Power Supplies",c:"Power & Battery",p:"₹249",img:"https://picsum.photos/seed/12v-smps-power-supplies/300/300"},
{n:"Breadboard Power Supply (MB102)",c:"Power & Battery",p:"₹79",img:"https://picsum.photos/seed/breadboard-power-supply-mb102/300/300"},
{n:"RTC Battery CR2032 Holders",c:"Power & Battery",img:"https://picsum.photos/seed/rtc-battery-cr2032-holders/300/300"},
{n:"MP1584EN Ultra Small DC-DC Step-Down Buck Converters",c:"Power & Battery",img:"https://picsum.photos/seed/mp1584en-ultra-small-dc-dc-step-down-buck-converters/300/300"},
{n:"XL4015 5A Step-Down Adjustable Regulators",c:"Power & Battery",img:"https://picsum.photos/seed/xl4015-5a-step-down-adjustable-regulators/300/300"},
{n:"XL4016 8A High Power Buck Converters",c:"Power & Battery",img:"https://picsum.photos/seed/xl4016-8a-high-power-buck-converters/300/300"},
{n:"LM2577 Step-Up Boost Modules",c:"Power & Battery",img:"https://picsum.photos/seed/lm2577-step-up-boost-modules/300/300"},
{n:"MT3608 DC-DC Boost Converters",c:"Power & Battery",img:"https://picsum.photos/seed/mt3608-dc-dc-boost-converters/300/300"},
{n:"XL6019 High Power Boost Modules",c:"Power & Battery",img:"https://picsum.photos/seed/xl6019-high-power-boost-modules/300/300"},
{n:"TPS61030 High Efficiency Boost Converters",c:"Power & Battery",img:"https://picsum.photos/seed/tps61030-high-efficiency-boost-converters/300/300"},
{n:"LM7809 Voltage Regulators",c:"Power & Battery",img:"https://picsum.photos/seed/lm7809-voltage-regulators/300/300"},
{n:"LM7824 Voltage Regulators",c:"Power & Battery",img:"https://picsum.photos/seed/lm7824-voltage-regulators/300/300"},
{n:"LT1083 High Current Adjustable Linear Regulators",c:"Power & Battery",img:"https://picsum.photos/seed/lt1083-high-current-adjustable-linear-regulators/300/300"},
{n:"LiFePO4 Battery Cells (32650, 26650)",c:"Power & Battery",img:"https://picsum.photos/seed/lifepo4-battery-cells-32650-26650/300/300"},
{n:"Nickel-Metal Hydride (NiMH) Rechargeable Cells",c:"Power & Battery",img:"https://picsum.photos/seed/nickel-metal-hydride-nimh-rechargeable-cells/300/300"},
{n:"Button Cell CR2032 Holders with Leads",c:"Power & Battery",img:"https://picsum.photos/seed/button-cell-cr2032-holders-with-leads/300/300"},
{n:"18650 Battery Spot Welders",c:"Power & Battery",img:"https://picsum.photos/seed/18650-battery-spot-welders/300/300"},
{n:"Nickel Strip Rolls for Battery Pack Making",c:"Power & Battery",img:"https://picsum.photos/seed/nickel-strip-rolls-for-battery-pack-making/300/300"},
{n:"Heat Resistant Battery Insulator Paper Rings",c:"Power & Battery",img:"https://picsum.photos/seed/heat-resistant-battery-insulator-paper-rings/300/300"},
{n:"BMS 3S/4S/5S with Balance Charging Circuits",c:"Power & Battery",p:"₹149",img:"https://picsum.photos/seed/bms-3s-4s-5s-with-balance-charging-circuits/300/300"},
{n:"Smart BMS with Bluetooth and UART",c:"Power & Battery",img:"https://picsum.photos/seed/smart-bms-with-bluetooth-and-uart/300/300"},
{n:"IMAX B6 Battery Balance Chargers",c:"Power & Battery",img:"https://picsum.photos/seed/imax-b6-battery-balance-chargers/300/300"},
{n:"12V Lead-Acid Battery Smart Chargers",c:"Power & Battery",img:"https://picsum.photos/seed/12v-lead-acid-battery-smart-chargers/300/300"},
{n:"Peltier Thermoelectric Coolers (TEC1-12706)",c:"Power & Battery",img:"https://picsum.photos/seed/peltier-thermoelectric-coolers-tec1-12706/300/300"},
{n:"High Voltage Boost Step-Up Generators",c:"Power & Battery",img:"https://picsum.photos/seed/high-voltage-boost-step-up-generators/300/300"},
{n:"Tesla Coil DIY Kits",c:"Power & Battery",img:"https://picsum.photos/seed/tesla-coil-diy-kits/300/300"},
{n:"Marx Generator Kits",c:"Power & Battery",img:"https://picsum.photos/seed/marx-generator-kits/300/300"},
{n:"Cockcroft-Walton Voltage Multipliers",c:"Power & Battery",img:"https://picsum.photos/seed/cockcroft-walton-voltage-multipliers/300/300"},
{n:"Ignition Coils for Projects",c:"Power & Battery",img:"https://picsum.photos/seed/ignition-coils-for-projects/300/300"},
{n:"Relay Modules (1-channel, 2-channel, 4-channel, 8-channel)",c:"Relays & Timers",img:"https://picsum.photos/seed/relay-modules-1-channel-2-channel-4-channel-8-channel/300/300"},
{n:"Solid State Relays (SSR-40DA, SSR-25DA)",c:"Relays & Timers",img:"https://picsum.photos/seed/solid-state-relays-ssr-40da-ssr-25da/300/300"},
{n:"16-Channel Optocoupler Relay Boards",c:"Relays & Timers",img:"https://picsum.photos/seed/16-channel-optocoupler-relay-boards/300/300"},
{n:"Bistable Latching Relay Modules",c:"Relays & Timers",img:"https://picsum.photos/seed/bistable-latching-relay-modules/300/300"},
{n:"Time Delay Relay Modules",c:"Relays & Timers",img:"https://picsum.photos/seed/time-delay-relay-modules/300/300"},
{n:"Multifunction Timer Control Panels",c:"Relays & Timers",img:"https://picsum.photos/seed/multifunction-timer-control-panels/300/300"},
{n:"Overvoltage and Undervoltage Protection Relay Boards",c:"Relays & Timers",img:"https://picsum.photos/seed/overvoltage-and-undervoltage-protection-relay-boards/300/300"},
{n:"Solid State Relays (SSR)",c:"Relays & Timers",img:"https://picsum.photos/seed/solid-state-relays-ssr/300/300"},
{n:"Electromagnetic Relays (5V, 12V)",c:"Relays & Timers",img:"https://picsum.photos/seed/electromagnetic-relays-5v-12v/300/300"},
{n:"Opto-Isolated Relay Boards",c:"Relays & Timers",img:"https://picsum.photos/seed/opto-isolated-relay-boards/300/300"},
{n:"3D Printer Controller Boards",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/3d-printer-controller-boards/300/300"},
{n:"Filament Dryers",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/filament-dryers/300/300"},
{n:"PTFE Teflon Tubes",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/ptfe-teflon-tubes/300/300"},
{n:"Bowden Extruders",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/bowden-extruders/300/300"},
{n:"Stepper Motor Heat Sinks",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/stepper-motor-heat-sinks/300/300"},
{n:"Endstop Mechanical Switches",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/endstop-mechanical-switches/300/300"},
{n:"Optical Limit Switches",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/optical-limit-switches/300/300"},
{n:"Print Surface PEI Sheets",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/print-surface-pei-sheets/300/300"},
{n:"2WD Robotics Chassis",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/2wd-robotics-chassis/300/300"},
{n:"4WD Robotics Chassis",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/4wd-robotics-chassis/300/300"},
{n:"Smart Robot Car Kits",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/smart-robot-car-kits/300/300"},
{n:"Rubber Tyres for Robots",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/rubber-tyres-for-robots/300/300"},
{n:"Caster Wheels",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/caster-wheels/300/300"},
{n:"Mecanum Wheels",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/mecanum-wheels/300/300"},
{n:"Linear Guide Rails and Slider Blocks",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/linear-guide-rails-and-slider-blocks/300/300"},
{n:"Lead Screws with Nuts (T8 Screws)",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/lead-screws-with-nuts-t8-screws/300/300"},
{n:"Timing Belts and Pulleys (GT2 System)",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/timing-belts-and-pulleys-gt2-system/300/300"},
{n:"Flexible Shaft Couplings (Aluminum Couplers)",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/flexible-shaft-couplings-aluminum-couplers/300/300"},
{n:"Nema 17 Stepper Motor Dampers",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/nema-17-stepper-motor-dampers/300/300"},
{n:"CNC Shield V3 for Arduino",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/cnc-shield-v3-for-arduino/300/300"},
{n:"RAMPS 1.4 / 1.6 3D Printer Controller Boards",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/ramps-1-4-1-6-3d-printer-controller-boards/300/300"},
{n:"3D Printer Extruder Hotends and Nozzles",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/3d-printer-extruder-hotends-and-nozzles/300/300"},
{n:"Heated Beds for 3D Printers",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/heated-beds-for-3d-printers/300/300"},
{n:"GT2 Timing Belts and Tensioners",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/gt2-timing-belts-and-tensioners/300/300"},
{n:"Corrugated Plastic Sheets for Robotics",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/corrugated-plastic-sheets-for-robotics/300/300"},
{n:"Acrylic Sheets (Laser Cut Grade)",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/acrylic-sheets-laser-cut-grade/300/300"},
{n:"PVC Foam Boards",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/pvc-foam-boards/300/300"},
{n:"Carbon Fiber Rods and Tubes",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/carbon-fiber-rods-and-tubes/300/300"},
{n:"Aluminum Extrusion Profiles (2020, 2040 Series)",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/aluminum-extrusion-profiles-2020-2040-series/300/300"},
{n:"T-Nuts and Spring Nuts for Aluminum Extrusion",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/t-nuts-and-spring-nuts-for-aluminum-extrusion/300/300"},
{n:"Corner Brackets and Joiner Plates",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/corner-brackets-and-joiner-plates/300/300"},
{n:"Slide-in Drop-in T-Nuts",c:"Robotics & 3D Printing",img:"https://picsum.photos/seed/slide-in-drop-in-t-nuts/300/300"},
{n:"Heat Shrink Tubes",c:"Connectors, Wires & Hardware",p:"₹99",img:"https://picsum.photos/seed/heat-shrink-tubes/300/300"},
{n:"Large Breadboards",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/large-breadboards/300/300"},
{n:"Small Breadboards",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/small-breadboards/300/300"},
{n:"Jumper Wires (Male-to-Male, Male-to-Female, Female-to-Female)",c:"Connectors, Wires & Hardware",p:"₹49",img:"https://picsum.photos/seed/jumper-wires-male-to-male-male-to-female-female-to-female/300/300"},
{n:"Ribbon Cables",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/ribbon-cables/300/300"},
{n:"Hook-up Wires",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/hook-up-wires/300/300"},
{n:"Perfboards",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/perfboards/300/300"},
{n:"Zero PCBs",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/zero-pcbs/300/300"},
{n:"Copper Clad Boards",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/copper-clad-boards/300/300"},
{n:"Zip Ties",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/zip-ties/300/300"},
{n:"Heat Sinks",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/heat-sinks/300/300"},
{n:"Nylon Spacers and Standoffs",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/nylon-spacers-and-standoffs/300/300"},
{n:"Brass Standoffs",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/brass-standoffs/300/300"},
{n:"Matrix Keypads (4x4, 4x3)",c:"Connectors, Wires & Hardware",p:"₹49",img:"https://picsum.photos/seed/matrix-keypads-4x4-4x3/300/300"},
{n:"Push Button Switches (Tactile Switches)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/push-button-switches-tactile-switches/300/300"},
{n:"Slide Switches",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/slide-switches/300/300"},
{n:"Toggle Switches",c:"Connectors, Wires & Hardware",p:"₹39",img:"https://picsum.photos/seed/toggle-switches/300/300"},
{n:"DIP Switches",c:"Connectors, Wires & Hardware",p:"₹19",img:"https://picsum.photos/seed/dip-switches/300/300"},
{n:"Rocker Switches",c:"Connectors, Wires & Hardware",p:"₹19",img:"https://picsum.photos/seed/rocker-switches/300/300"},
{n:"Limit Switches",c:"Connectors, Wires & Hardware",p:"₹29",img:"https://picsum.photos/seed/limit-switches/300/300"},
{n:"Joystick Modules",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/joystick-modules/300/300"},
{n:"Heat Sinks with Fans for Peltier",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/heat-sinks-with-fans-for-peltier/300/300"},
{n:"Thermal Paste / Compound",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/thermal-paste-compound/300/300"},
{n:"Copper Heat Sinks",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/copper-heat-sinks/300/300"},
{n:"Aluminum Enclosures / Project Boxes",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/aluminum-enclosures-project-boxes/300/300"},
{n:"Plastic ABS Project Boxes",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/plastic-abs-project-boxes/300/300"},
{n:"Waterproof Junction Boxes",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/waterproof-junction-boxes/300/300"},
{n:"Female DC Power Jacks",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/female-dc-power-jacks/300/300"},
{n:"Male DC Power Plugs",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/male-dc-power-plugs/300/300"},
{n:"USB Type-A Connectors",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/usb-type-a-connectors/300/300"},
{n:"Micro USB Connectors",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/micro-usb-connectors/300/300"},
{n:"Type-C USB Connectors",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/type-c-usb-connectors/300/300"},
{n:"Mini USB Connectors",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/mini-usb-connectors/300/300"},
{n:"Audio Jacks (3.5mm Mono & Stereo)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/audio-jacks-3-5mm-mono-stereo/300/300"},
{n:"RCA Connectors",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/rca-connectors/300/300"},
{n:"Banana Plugs and Jacks",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/banana-plugs-and-jacks/300/300"},
{n:"Alligator Clips (Crocodile Clips)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/alligator-clips-crocodile-clips/300/300"},
{n:"IC Sockets (8-pin, 14-pin, 16-pin, 28-pin, 40-pin)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/ic-sockets-8-pin-14-pin-16-pin-28-pin-40-pin/300/300"},
{n:"Berg Strips (Male and Female)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/berg-strips-male-and-female/300/300"},
{n:"Pin Headers (Breakaway headers)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/pin-headers-breakaway-headers/300/300"},
{n:"Screw Terminal Blocks (2-pin, 3-pin)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/screw-terminal-blocks-2-pin-3-pin/300/300"},
{n:"IDC Connectors and Flat Ribbons",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/idc-connectors-and-flat-ribbons/300/300"},
{n:"Heat Shrinkable Sleeves",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/heat-shrinkable-sleeves/300/300"},
{n:"Electrical Insulation Tape",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/electrical-insulation-tape/300/300"},
{n:"Double-Sided Foam Tape",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/double-sided-foam-tape/300/300"},
{n:"SMD Practice PCBs",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/smd-practice-pcbs/300/300"},
{n:"Silicon Tubing / Pipes for Water Pumps",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/silicon-tubing-pipes-for-water-pumps/300/300"},
{n:"Polyimide Kapton Tape",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/polyimide-kapton-tape/300/300"},
{n:"High-Temperature Teflon Tape",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/high-temperature-teflon-tape/300/300"},
{n:"Masking Tape",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/masking-tape/300/300"},
{n:"Self-Fusing Silicone Tape",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/self-fusing-silicone-tape/300/300"},
{n:"Plastic Rivets and Push Pins",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/plastic-rivets-and-push-pins/300/300"},
{n:"Nylon Cable Glands",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/nylon-cable-glands/300/300"},
{n:"Waterproof Cable Connectors (GX12, GX16 Aviation Plugs)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/waterproof-cable-connectors-gx12-gx16-aviation-plugs/300/300"},
{n:"Heavy Duty Terminal Strips",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/heavy-duty-terminal-strips/300/300"},
{n:"Ceramic Terminal Blocks",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/ceramic-terminal-blocks/300/300"},
{n:"Bus Bars",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/bus-bars/300/300"},
{n:"Copper Lug Terminals",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/copper-lug-terminals/300/300"},
{n:"Heat Shrink Solder Seal Wire Connectors",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/heat-shrink-solder-seal-wire-connectors/300/300"},
{n:"Bullet Connectors",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/bullet-connectors/300/300"},
{n:"Spade Terminals (Male and Female)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/spade-terminals-male-and-female/300/300"},
{n:"Ring Terminals",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/ring-terminals/300/300"},
{n:"Wire Ferrule Terminals (Bootlace Ferrules)",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/wire-ferrule-terminals-bootlace-ferrules/300/300"},
{n:"Anti-Static Bags",c:"Connectors, Wires & Hardware",img:"https://picsum.photos/seed/anti-static-bags/300/300"},
{n:"Soldering Iron Tips (T12 series, 900M series)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/soldering-iron-tips-t12-series-900m-series/300/300"},
{n:"Soldering Iron Stands with Cleaning Sponges",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/soldering-iron-stands-with-cleaning-sponges/300/300"},
{n:"Brass Wire Tip Cleaners",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/brass-wire-tip-cleaners/300/300"},
{n:"Lead-Free Solder Wire",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/lead-free-solder-wire/300/300"},
{n:"Rosin Core Solder Wire",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/rosin-core-solder-wire/300/300"},
{n:"Liquid Soldering Flux Pens",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/liquid-soldering-flux-pens/300/300"},
{n:"No-Clean Flux Paste",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/no-clean-flux-paste/300/300"},
{n:"Desoldering Braid Wicks",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/desoldering-braid-wicks/300/300"},
{n:"Thermal Conductive Silicone Grease",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/thermal-conductive-silicone-grease/300/300"},
{n:"UV Curing Solder Mask Inks",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/uv-curing-solder-mask-inks/300/300"},
{n:"PCB Drill Bits",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/pcb-drill-bits/300/300"},
{n:"Mini Hand Drills",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/mini-hand-drills/300/300"},
{n:"Pin Vices",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/pin-vices/300/300"},
{n:"Ceramic Tweezers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/ceramic-tweezers/300/300"},
{n:"ESD Safe Cleaning Brushes",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/esd-safe-cleaning-brushes/300/300"},
{n:"Magnifying Lamps with LED Lights",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/magnifying-lamps-with-led-lights/300/300"},
{n:"Digital Multimeter Clamp Meters",c:"Tools & Test Equipment",p:"₹849",img:"https://picsum.photos/seed/digital-multimeter-clamp-meters/300/300"},
{n:"LCR Meters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/lcr-meters/300/300"},
{n:"Insulation Resistance Testers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/insulation-resistance-testers/300/300"},
{n:"DC Bench Power Supplies",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/dc-bench-power-supplies/300/300"},
{n:"Programmable Electronic DC Loads",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/programmable-electronic-dc-loads/300/300"},
{n:"Function Generators",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/function-generators/300/300"},
{n:"Digital Storage Oscilloscopes (DSO)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/digital-storage-oscilloscopes-dso/300/300"},
{n:"Logic Analyzers (Saleae 24M 8CH)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/logic-analyzers-saleae-24m-8ch/300/300"},
{n:"Soldering Irons",c:"Tools & Test Equipment",p:"₹199",img:"https://picsum.photos/seed/soldering-irons/300/300"},
{n:"Temperature Controlled Soldering Stations",c:"Tools & Test Equipment",p:"₹1,499",img:"https://picsum.photos/seed/temperature-controlled-soldering-stations/300/300"},
{n:"Solder Wire",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/solder-wire/300/300"},
{n:"Soldering Flux",c:"Tools & Test Equipment",p:"₹29",img:"https://picsum.photos/seed/soldering-flux/300/300"},
{n:"Desoldering Pumps",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/desoldering-pumps/300/300"},
{n:"PCB Cleaner (IPA)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/pcb-cleaner-ipa/300/300"},
{n:"Digital Multimeters",c:"Tools & Test Equipment",p:"₹249",img:"https://picsum.photos/seed/digital-multimeters/300/300"},
{n:"Multimeter Probes",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/multimeter-probes/300/300"},
{n:"Soldering Mats",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/soldering-mats/300/300"},
{n:"Logic Analyzers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/logic-analyzers/300/300"},
{n:"Oscilloscopes",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/oscilloscopes/300/300"},
{n:"Screwdrivers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/screwdrivers/300/300"},
{n:"Wire Strippers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/wire-strippers/300/300"},
{n:"Hot Glue Guns",c:"Tools & Test Equipment",p:"₹249",img:"https://picsum.photos/seed/hot-glue-guns/300/300"},
{n:"Hot Glue Sticks",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/hot-glue-sticks/300/300"},
{n:"Test Hook Clips",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/test-hook-clips/300/300"},
{n:"Solder Sucker / Desoldering Pump",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/solder-sucker-desoldering-pump/300/300"},
{n:"Desoldering Wick / Braid",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/desoldering-wick-braid/300/300"},
{n:"PCB Holder / Third Hand Tool",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/pcb-holder-third-hand-tool/300/300"},
{n:"Precision Screwdriver Sets",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/precision-screwdriver-sets/300/300"},
{n:"Wire Stripper and Cutter Pliers",c:"Tools & Test Equipment",p:"₹149",img:"https://picsum.photos/seed/wire-stripper-and-cutter-pliers/300/300"},
{n:"Long Nose Pliers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/long-nose-pliers/300/300"},
{n:"Side Cutter Pliers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/side-cutter-pliers/300/300"},
{n:"Tweezers (Antistatic ESD Safe)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/tweezers-antistatic-esd-safe/300/300"},
{n:"Multimeter Test Leads (Extra fine tip)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/multimeter-test-leads-extra-fine-tip/300/300"},
{n:"Component Sorting Storage Boxes",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/component-sorting-storage-boxes/300/300"},
{n:"Ferrule Crimping Tool Kits",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/ferrule-crimping-tool-kits/300/300"},
{n:"Ratchet Wire Crimpers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/ratchet-wire-crimpers/300/300"},
{n:"Heavy Duty Cable Lug Crimpers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/heavy-duty-cable-lug-crimpers/300/300"},
{n:"Coaxial Cable Strippers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/coaxial-cable-strippers/300/300"},
{n:"Automatic Wire Stripping Pliers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/automatic-wire-stripping-pliers/300/300"},
{n:"Diagonal Cutting Pliers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/diagonal-cutting-pliers/300/300"},
{n:"Needle Nose Pliers with Cutters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/needle-nose-pliers-with-cutters/300/300"},
{n:"Circlip Pliers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/circlip-pliers/300/300"},
{n:"Hex Allen Key Sets (Metric and Imperial)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/hex-allen-key-sets-metric-and-imperial/300/300"},
{n:"Torx Screwdriver Sets",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/torx-screwdriver-sets/300/300"},
{n:"Precision Tweezers Sets",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/precision-tweezers-sets/300/300"},
{n:"Magnetic Parts Trays",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/magnetic-parts-trays/300/300"},
{n:"ESD Grounding Mats and Wrist Straps",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/esd-grounding-mats-and-wrist-straps/300/300"},
{n:"Component Bin Storage Cabinets",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/component-bin-storage-cabinets/300/300"},
{n:"Plastic Drawer Organizer Boxes",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/plastic-drawer-organizer-boxes/300/300"},
{n:"Heavy Duty Storage Racks",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/heavy-duty-storage-racks/300/300"},
{n:"Label Printers for Component Bins",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/label-printers-for-component-bins/300/300"},
{n:"Magnifying Headsets with Interchangeable Lenses",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/magnifying-headsets-with-interchangeable-lenses/300/300"},
{n:"USB Digital Microscopes for Soldering Inspection",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/usb-digital-microscopes-for-soldering-inspection/300/300"},
{n:"Hot Air Rework Stations (858D series)",c:"Tools & Test Equipment",p:"₹4,499",img:"https://picsum.photos/seed/hot-air-rework-stations-858d-series/300/300"},
{n:"SMD Hot Plate Preheaters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/smd-hot-plate-preheaters/300/300"},
{n:"BGA Reballing Stencils",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/bga-reballing-stencils/300/300"},
{n:"Solder Paste Syringes",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/solder-paste-syringes/300/300"},
{n:"Solder Paste Dispensers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/solder-paste-dispensers/300/300"},
{n:"UV Shadowless Glue",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/uv-shadowless-glue/300/300"},
{n:"UV Curing Flashlights",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/uv-curing-flashlights/300/300"},
{n:"Thermal Imaging Cameras for PCB Diagnostics",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/thermal-imaging-cameras-for-pcb-diagnostics/300/300"},
{n:"Digital Wattmeters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/digital-wattmeters/300/300"},
{n:"AC Power Meters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/ac-power-meters/300/300"},
{n:"Plug-in Electricity Monitors",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/plug-in-electricity-monitors/300/300"},
{n:"Infrared Thermometers (Laser Pyrometers)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/infrared-thermometers-laser-pyrometers/300/300"},
{n:"Sound Level Meters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/sound-level-meters/300/300"},
{n:"Lux Meters (Digital Light Meters)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/lux-meters-digital-light-meters/300/300"},
{n:"Anemometers (Wind Speed Meters)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/anemometers-wind-speed-meters/300/300"},
{n:"Tachometers (Optical and Contact RPM Meters)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/tachometers-optical-and-contact-rpm-meters/300/300"},
{n:"Gas Leak Detectors",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/gas-leak-detectors/300/300"},
{n:"Water Quality Multi-Meters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/water-quality-multi-meters/300/300"},
{n:"Soil Test Kits",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/soil-test-kits/300/300"},
{n:"Digital Refractometers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/digital-refractometers/300/300"},
{n:"Electronic Stethoscopes",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/electronic-stethoscopes/300/300"},
{n:"Signal Generators",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/signal-generators/300/300"},
{n:"Frequency Counters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/frequency-counters/300/300"},
{n:"Transistor Testers (LCR-T4 / GM328)",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/transistor-testers-lcr-t4-gm328/300/300"},
{n:"Component ID Testers",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/component-id-testers/300/300"},
{n:"ESD Safe Lab Coats",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/esd-safe-lab-coats/300/300"},
{n:"Safety Glasses",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/safety-glasses/300/300"},
{n:"Nitrile Gloves",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/nitrile-gloves/300/300"},
{n:"Smoke Absorbers for Soldering",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/smoke-absorbers-for-soldering/300/300"},
{n:"Mini Exhaust Fans",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/mini-exhaust-fans/300/300"},
{n:"Desktop Fume Extractors with Activated Carbon Filters",c:"Tools & Test Equipment",img:"https://picsum.photos/seed/desktop-fume-extractors-with-activated-carbon-filters/300/300"},
{n:"Rain Water Sensor Module",c:"Sensors",p:"₹49",img:"https://picsum.photos/seed/rain-water-sensor-module/300/300"},
{n:"Flame Sensor Module",c:"Sensors",p:"₹49",img:"https://picsum.photos/seed/flame-sensor-module/300/300"},
{n:"LDR Light Sensor Module",c:"Sensors",p:"₹39",img:"https://picsum.photos/seed/ldr-light-sensor-module/300/300"},
{n:"MG90S Mini Metal Gear Servo",c:"Motors, Actuators & Drivers",p:"₹199",img:"https://picsum.photos/seed/mg90s-mini-metal-gear-servo/300/300"},
{n:"12V DC Geared Motor",c:"Motors, Actuators & Drivers",p:"₹199",img:"https://picsum.photos/seed/12v-dc-geared-motor/300/300"},
{n:"16x2 LCD Display with I2C Module",c:"Displays & Audio",p:"₹199",img:"https://picsum.photos/seed/16x2-lcd-display-with-i2c-module/300/300"},
{n:"0.96 inch OLED Display (I2C)",c:"Displays & Audio",p:"₹249",img:"https://picsum.photos/seed/0-96-inch-oled-display-i2c/300/300"},
{n:"Solderless Breadboard (840 Points)",c:"Connectors, Wires & Hardware",p:"₹149",img:"https://picsum.photos/seed/solderless-breadboard-840-points/300/300"},
{n:"9V Battery with Snap Connector",c:"Power & Battery",p:"₹39",img:"https://picsum.photos/seed/9v-battery-with-snap-connector/300/300"},
{n:"1-Channel 5V Relay Module",c:"Relays & Timers",p:"₹59",img:"https://picsum.photos/seed/1-channel-5v-relay-module/300/300"},
{n:"4-Channel 5V Relay Module",c:"Relays & Timers",p:"₹149",img:"https://picsum.photos/seed/4-channel-5v-relay-module/300/300"},
{n:"Resistors Pack (1/4 Watt, Assorted)",c:"Basic Components",p:"₹69",img:"https://picsum.photos/seed/resistors-pack-1-4-watt-assorted/300/300"},
{n:"LED Assorted Pack (Pack of 50)",c:"Basic Components",p:"₹79",img:"https://picsum.photos/seed/led-assorted-pack-pack-of-50/300/300"},
{n:"Raspberry Pi 4 Model B (4GB)",c:"Development Boards",p:"₹6,999",img:"https://picsum.photos/seed/raspberry-pi-4-model-b-4gb/300/300"},
{n:"Raspberry Pi 5 (8GB)",c:"Development Boards",p:"₹10,999",img:"https://picsum.photos/seed/raspberry-pi-5-8gb/300/300"},
{n:"STM32F103C8T6 (Blue Pill Board)",c:"Development Boards",p:"₹299",img:"https://picsum.photos/seed/stm32f103c8t6-blue-pill-board/300/300"},
{n:"ATTiny85 Development Board",c:"Development Boards",p:"₹199",img:"https://picsum.photos/seed/attiny85-development-board/300/300"},
{n:"Raspberry Pi Pico W (WiFi built-in)",c:"Development Boards",p:"₹699",img:"https://picsum.photos/seed/raspberry-pi-pico-w-wifi-built-in/300/300"},
{n:"7805 Voltage Regulator (5V)",c:"Power & Battery",p:"₹19",img:"https://picsum.photos/seed/7805-voltage-regulator-5v/300/300"},
{n:"7812 Voltage Regulator (12V)",c:"Power & Battery",p:"₹19",img:"https://picsum.photos/seed/7812-voltage-regulator-12v/300/300"},
{n:"BC547 NPN Transistor (Pack of 10)",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/bc547-npn-transistor-pack-of-10/300/300"},
{n:"2N2222 NPN Transistor (Pack of 10)",c:"Basic Components",p:"₹29",img:"https://picsum.photos/seed/2n2222-npn-transistor-pack-of-10/300/300"},
{n:"10K Potentiometer (Rotary)",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/10k-potentiometer-rotary/300/300"},
{n:"Preset Variable Resistor (Trim Pot)",c:"Basic Components",p:"₹19",img:"https://picsum.photos/seed/preset-variable-resistor-trim-pot/300/300"},
{n:"Active Buzzer (5V)",c:"Displays & Audio",p:"₹19",img:"https://picsum.photos/seed/active-buzzer-5v/300/300"},
{n:"Passive Buzzer (5V)",c:"Displays & Audio",p:"₹29",img:"https://picsum.photos/seed/passive-buzzer-5v/300/300"},
{n:"433MHz RF Transmitter-Receiver Pair",c:"Communication Modules",p:"₹149",img:"https://picsum.photos/seed/433mhz-rf-transmitter-receiver-pair/300/300"},
{n:"ESP8266 ESP-01 WiFi Module",c:"Communication Modules",p:"₹199",img:"https://picsum.photos/seed/esp8266-esp-01-wifi-module/300/300"},
{n:"MQ-2 Gas / Smoke Sensor",c:"Sensors",p:"₹149",img:"https://picsum.photos/seed/mq-2-gas-smoke-sensor/300/300"},
{n:"MQ-135 Air Quality Sensor",c:"Sensors",p:"₹199",img:"https://picsum.photos/seed/mq-135-air-quality-sensor/300/300"},
{n:"LM35 Precision Temperature Sensor",c:"Sensors",p:"₹59",img:"https://picsum.photos/seed/lm35-precision-temperature-sensor/300/300"},
{n:"Pulse / Heart Rate Sensor",c:"Sensors",p:"₹249",img:"https://picsum.photos/seed/pulse-heart-rate-sensor/300/300"},
{n:"Load Cell Sensor (5kg) with HX711 Module",c:"Sensors",p:"₹299",img:"https://picsum.photos/seed/load-cell-sensor-5kg-with-hx711-module/300/300"},
{n:"IR Obstacle Avoidance Sensor Module",c:"Sensors",p:"₹39",img:"https://picsum.photos/seed/ir-obstacle-avoidance-sensor-module/300/300"},
{n:"Sound / Voice Sensor Module",c:"Sensors",p:"₹59",img:"https://picsum.photos/seed/sound-voice-sensor-module/300/300"},
{n:"18650 Single Cell Battery Holder",c:"Power & Battery",p:"₹39",img:"https://picsum.photos/seed/18650-single-cell-battery-holder/300/300"},
{n:"Solar Panel (5V / 1W)",c:"Power & Battery",p:"₹149",img:"https://picsum.photos/seed/solar-panel-5v-1w/300/300"},
{n:"Tactile Push Buttons (Pack of 10)",c:"Connectors, Wires & Hardware",p:"₹29",img:"https://picsum.photos/seed/tactile-push-buttons-pack-of-10/300/300"},
{n:"2-Channel 5V Relay Module",c:"Relays & Timers",p:"₹99",img:"https://picsum.photos/seed/2-channel-5v-relay-module/300/300"},
{n:"8-Channel 5V Relay Module",c:"Relays & Timers",p:"₹299",img:"https://picsum.photos/seed/8-channel-5v-relay-module/300/300"},
{n:"Soldering Lead Wire (50g)",c:"Tools & Test Equipment",p:"₹149",img:"https://picsum.photos/seed/soldering-lead-wire-50g/300/300"},
{n:"Zero PCB / Dot PCB Board (4x6 cm)",c:"Connectors, Wires & Hardware",p:"₹19",img:"https://picsum.photos/seed/zero-pcb-dot-pcb-board-4x6-cm/300/300"},
{n:"BO Motor Wheels (Pair)",c:"Robotics & 3D Printing",p:"₹49",img:"https://picsum.photos/seed/bo-motor-wheels-pair/300/300"},
{n:"Mini Castor Wheel",c:"Robotics & 3D Printing",p:"₹39",img:"https://picsum.photos/seed/mini-castor-wheel/300/300"},
{n:"Copper Clad Board (for PCB etching)",c:"Connectors, Wires & Hardware",p:"₹49",img:"https://picsum.photos/seed/copper-clad-board-for-pcb-etching/300/300"},
{n:"Generic / Local 10mm Impact Drill Machine",c:"Power Tools & Equipment",p:"₹1,499",img:"https://picsum.photos/seed/generic-local-10mm-impact-drill-machine/300/300"},
{n:"Bosch GSB 450 Impact Drill (10mm)",c:"Power Tools & Equipment",p:"₹3,499",img:"https://picsum.photos/seed/bosch-gsb-450-impact-drill-10mm/300/300"},
{n:"Bosch GSB 600 Professional Impact Drill (13mm)",c:"Power Tools & Equipment",p:"₹3,999",img:"https://picsum.photos/seed/bosch-gsb-600-professional-impact-drill-13mm/300/300"},
{n:"Cordless Drill Machine (12V with Battery & Charger)",c:"Power Tools & Equipment",p:"₹3,499",img:"https://picsum.photos/seed/cordless-drill-machine-12v-with-battery-charger/300/300"},
{n:"Heavy Duty Hammer Drill Machine (Professional)",c:"Power Tools & Equipment",p:"₹5,999",img:"https://picsum.photos/seed/heavy-duty-hammer-drill-machine-professional/300/300"},
{n:"Rechargeable Cordless Electric Screwdriver (47-in-1 Kit with Bits)",c:"Power Tools & Equipment",p:"₹1,499",img:"https://picsum.photos/seed/rechargeable-cordless-electric-screwdriver-47-in-1-kit-with-bits/300/300"},
{n:"INGCO / Bosch 4V Lithium-Ion Cordless Screwdriver",c:"Power Tools & Equipment",p:"₹2,499",img:"https://picsum.photos/seed/ingco-bosch-4v-lithium-ion-cordless-screwdriver/300/300"},
{n:"Mini Precision Electric Screwdriver (For Laptops/Mobiles)",c:"Power Tools & Equipment",p:"₹849",img:"https://picsum.photos/seed/mini-precision-electric-screwdriver-for-laptops-mobiles/300/300"},
{n:"Angle Grinder (4-inch, Heavy Duty)",c:"Power Tools & Equipment",p:"₹2,499",img:"https://picsum.photos/seed/angle-grinder-4-inch-heavy-duty/300/300"},
{n:"Electric Marble / Tile Cutter",c:"Power Tools & Equipment",p:"₹2,999",img:"https://picsum.photos/seed/electric-marble-tile-cutter/300/300"},
{n:"Industrial Heat Gun (2000W with Temperature Control)",c:"Power Tools & Equipment",p:"₹1,499",img:"https://picsum.photos/seed/industrial-heat-gun-2000w-with-temperature-control/300/300"},
{n:"Electric Jigsaw (For Wood and Plastic Cutting)",c:"Power Tools & Equipment",p:"₹3,999",img:"https://picsum.photos/seed/electric-jigsaw-for-wood-and-plastic-cutting/300/300"},
{n:"Electric Blowers (For Dust Cleaning)",c:"Power Tools & Equipment",p:"₹1,499",img:"https://picsum.photos/seed/electric-blowers-for-dust-cleaning/300/300"},
{n:"Heavy Duty Electric Glue Gun (100W)",c:"Power Tools & Equipment",p:"₹499",img:"https://picsum.photos/seed/heavy-duty-electric-glue-gun-100w/300/300"},
];